name: validate_rut
description: A Dart package for the validation and formatting of the Chilean Unique Tax Role (RUT).
version: 0.1.0
author: Tomás Ortega - ortegaxc.05@gmail.com
homepage: https://github.com/ortegaxc/validate-rut

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
