name: validate_rut
description: RUT Validator is a Dart package that provides utilities for the validation and formatting of the Chilean Rol Único Tributario (RUT). This is a unique identifier used in Chile for both businesses and individuals. The utilities in this package implement the official algorithm published by the Chilean registry office.
version: 0.1.0
author: Tomás Ortega - ortegaxc.05@gmail.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
