name: validate_rut
description: A Dart package for the validation and formatting of the Chilean Unique Tax Role (RUT).
version: 0.3.0
homepage: https://github.com/ortegaxc/validate-rut
# author: Tomás Ortega - ortegaxc.05@gmail.com

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
